version: 2
jobs:
  build:
    
    working_directory: ~/marketbasket-sbp-sample

    docker:
      - image: circleci/openjdk:11-jdk-stretch

    steps:

      - checkout

      - restore_cache:
          key: marketbasket-sbp-sample-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: marketbasket-sbp-sample-{{ checksum "pom.xml" }}
      
      - run: mvn package
